### ISSUE TITLE
Design: Node 를 띄우고 Pod 띄워서 스케일아웃 명령어 연습

### ISSUE THREAD

**Issue by Han-Joon-Hyeok** [42Cluster-Seoul/System-Design#6]
CKA 강의 실습하기

**Comment by Han-Joon-Hyeok** [comment]
# 개요

- 실행 환경 : Udemy CKA 자격증 대비 강좌에서 제공하는 샌드박스 (controlplane 노드 안에서 작업)
- 목표 : 
  1. Replicaset 을 정의한 yaml 파일을 작성한다.
  2. `kubectl` 명령어를 이용해서 replicaset 을 생성한다.
  3. `kubectl` 명령어를 이용해서 pod 개수를 조절한다.

# 1. Replicaset 정의

```yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
```
